FROM bind9

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"

RUN git clone https://github.com/stateafl/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    rm as && \
    cd llvm_mode && make $MAKE_OPT

# Set up environment variables for StateAFL
ENV AFL_PATH=${STATEAFL}
ENV PATH=${STATEAFL}:${PATH}


# Dedicated instrumented version for StateAFL
RUN cd $WORKDIR && \
    tar -xf bind-9.18.9.tar.xz && mv bind-9.18.9 bind-stateafl && \
    cd bind-stateafl && \
    ./configure \
    CC=${STATEAFL}/afl-clang-fast \
    --disable-doh \
    --prefix=$WORKDIR/bind-stateafl/build && \
    make $MAKE_OPT && make install

COPY --chown=ubuntu:ubuntu in-dns-replay ${WORKDIR}/in-dns-replay
COPY --chown=ubuntu:ubuntu run-stateafl.sh ${WORKDIR}/run-stateafl

