from forked-daapd

USER root
RUN apt-get -y update && apt-get -y install make \
    cmake gettext libtool libsqlite3-dev \
    gettext-base libelf-dev libc6-dbg cmake-curses-gui

USER ubuntu
WORKDIR /home/ubuntu
ENV SNAPFUZZ="/home/ubuntu/snapfuzz"

# These are the "stock" fuzzers, but we only want the modified ones for snapfuzz
# So remove to avoid confusion.
RUN rm -rf aflnet aflnwe

RUN git clone --recurse-submodules https://github.com/srg-imperial/SnapFuzz.git $SNAPFUZZ && \
    cd snapfuzz/SaBRe/plugins && \
    ln -s ../../snapfuzz snapfuzz && \
    cd .. && mkdir build && cd build && \
    cmake .. && make $MAKE_OPT

RUN cd /home/ubuntu/snapfuzz && \
    git clone https://github.com/andronat/aflnet.git --branch mymaster --single-branch && \
    cd aflnet && \
    make clean all && \
    cd llvm_mode && \
    make

ENV AFLNET="/home/ubuntu/snapfuzz/aflnet"
ENV PATH="${PATH}:${AFLNET}:/home/ubuntu/.local/bin:${WORKDIR}"
ENV AFL_PATH="${AFLNET}"

RUN cd $WORKDIR/forked-daapd && \
    make clean && \
    autoreconf -i && \
    CC="$AFLNET/afl-clang-fast" CFLAGS="-DSQLITE_CORE" ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var  --disable-mpd --disable-itunes --disable-lastfm --disable-spotify --disable-verification  --disable-shared --enable-static && \
    AFL_USE_ASAN=1 make -C src/ SMARTPL2SQL.c SMARTPL.c DAAP2SQL.c DAAPLexer.c RSPLexer.c RSP2SQL.c && \
    AFL_USE_ASAN=1 make clean all $MAKE_OPT

RUN cd $WORKDIR && \
    cp $SNAPFUZZ/SaBRe/build/sabre .
