from proftpd

USER root
RUN apt-get -y update && apt-get -y install make \
    cmake gettext libtool libsqlite3-dev \
    gettext-base libelf-dev libc6-dbg cmake-curses-gui

USER ubuntu
WORKDIR /home/ubuntu
ENV SNAPFUZZ="/home/ubuntu/snapfuzz"

# These are the "stock" fuzzers, but we only want the modified ones for snapfuzz
# So remove to avoid confusion.
RUN rm -rf aflnet aflnwe

RUN git clone --recurse-submodules https://github.com/srg-imperial/SnapFuzz.git $SNAPFUZZ && \
    cd snapfuzz/SaBRe/plugins && \
    ln -s ../../snapfuzz snapfuzz && \
    cd .. && mkdir build && cd build && \
    cmake .. && make $MAKE_OPT

RUN cd /home/ubuntu/snapfuzz && \
    git clone https://github.com/andronat/aflnet.git --branch mymaster --single-branch && \
    cd aflnet && \
    make clean all && \
    cd llvm_mode && \
    make

ENV AFLNET="/home/ubuntu/snapfuzz/aflnet"
ENV PATH="${PATH}:${AFLNET}:/home/ubuntu/.local/bin:${WORKDIR}"
ENV AFL_PATH="${AFLNET}"

RUN cd $WORKDIR && rm -rf proftpd

# Set up ProFTPD for fuzzing
RUN cd ${WORKDIR} && \
   git clone https://github.com/proftpd/proftpd.git && \
    cd proftpd && \
    git checkout 4017eff8 && \
    CC="$AFLNET/afl-clang-fast" CXX="$AFLNET/afl-clang-fast++" ./configure --enable-devel=nodaemon:nofork && \
    AFL_USE_ASAN=1 make $MAKE_OPT

RUN cd $WORKDIR/proftpd && \
    cp $SNAPFUZZ/SaBRe/build/sabre .
